/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DatSketch (https://sketchfab.com/DatSketch)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/apple-iphone-13-pro-max-4328dea00e47497dbeac73c556121bc9
title: Apple iPhone 13 Pro Max
*/

import React, { useRef, useLayoutEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";

export default function Model5({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/shoes.gltf");

  let camera = useThree((state) => state.camera);

  useLayoutEffect(() => {
    camera.position.set(-0.1,0.4,5);
    materials.lambert.color.set("#9BB5CE");
    console.log(nodes)
    if(window.matchMedia("(max-width: 48em)").matches){
      camera.fov = 18;
      camera.updateProjectionMatrix();
    }
        
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI+Math.PI/4, Math.PI, 0]}>
        <group  rotation={[Math.PI, 0, 0]} scale={1}>
        <mesh
        castShadow
        geometry={nodes.shoes.geometry}
        material={materials.lambert}
        material-roughness={1}
        dispose={null}>
     
      </mesh>
      <mesh
        castShadow
        geometry={nodes.shoes002.geometry}
        material={materials.Material016}
        material-roughness={1}
        dispose={null}>
     
      </mesh>
      <mesh
        castShadow
        geometry={nodes.shoes003.geometry}
        material={materials.MaterialBlack003}
        material-roughness={1}
        dispose={null}>
     
      </mesh>
      <mesh
        castShadow
        geometry={nodes.shoes004.geometry}
        material={materials.Material017}
        material-roughness={1}
        dispose={null}>
     
      </mesh>
      <mesh
        castShadow
        geometry={nodes.shoes005.geometry}
        material={materials.Laces003}
        material-roughness={1}
        dispose={null}>
     
      </mesh>
      <mesh
        castShadow
        geometry={nodes.shoes006.geometry}
        material={materials.Material018}
        material-roughness={1}
        dispose={null}>
     
      </mesh>
      <mesh
        castShadow
        geometry={nodes.shoes007.geometry}
        material={materials.FrontRubber003}
        material-roughness={1}
        dispose={null}>
     
      </mesh>
      <mesh
        castShadow
        geometry={nodes.shoesw.geometry}
        material={materials.White003}
        material-roughness={1}
        dispose={null}>
     
      </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/shoes.gltf");
